"use client"
import { useEffect, useState } from 'react'
import { formatCurrency } from '@/lib/utils'
import { Plus, Package, Search, Edit2, Trash2, X } from 'lucide-react'
export default function InventoryPage() {
  const [products, setProducts] = useState<any[]>([]); const [search, setSearch] = useState(''); const [showForm, setShowForm] = useState(false); const [editing, setEditing] = useState<any>(null); const [loading, setLoading] = useState(true); const [form, setForm] = useState({ name: '', description: '', costPrice: '', sellingPrice: '', stockQuantity: '', unit: 'pcs' }); const [saving, setSaving] = useState(false); const [restockId, setRestockId] = useState<string|null>(null); const [restockQty, setRestockQty] = useState('')
  useEffect(() => { loadProducts() }, [])
  async function loadProducts() { const d = await fetch('/api/products').then(r => r.json()); setProducts(Array.isArray(d)?d:[]); setLoading(false) }
  async function handleSubmit(e: React.FormEvent) { e.preventDefault(); setSaving(true); const p = { name: form.name, description: form.description, costPrice: parseFloat(form.costPrice), sellingPrice: parseFloat(form.sellingPrice), stockQuantity: parseInt(form.stockQuantity), unit: form.unit }; if (editing) await fetch('/api/products', { method: 'PUT', headers: {'Content-Type':'application/json'}, body: JSON.stringify({id:editing.id,...p}) }); else await fetch('/api/products', { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify(p) }); resetForm(); loadProducts() }
  async function handleRestock(pid: string) { const q = parseInt(restockQty); if (!q||q<=0) return; await fetch('/api/products/restock', { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({productId:pid,quantity:q}) }); setRestockId(null); setRestockQty(''); loadProducts() }
  async function handleDelete(id: string) { if (!confirm('Delete?')) return; await fetch(`/api/products?id=${id}`, {method:'DELETE'}); loadProducts() }
  function resetForm() { setForm({name:'',description:'',costPrice:'',sellingPrice:'',stockQuantity:'',unit:'pcs'}); setEditing(null); setShowForm(false); setSaving(false) }
  function startEdit(p: any) { setForm({name:p.name,description:p.description,costPrice:String(p.costPrice),sellingPrice:String(p.sellingPrice),stockQuantity:String(p.stockQuantity),unit:p.unit}); setEditing(p); setShowForm(true) }
  const filtered = products.filter(p => p.name.toLowerCase().includes(search.toLowerCase()))
  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4"><div><h1 className="text-2xl font-bold text-gray-900">Inventory</h1><p className="text-gray-500 mt-1">{products.length} products</p></div><button onClick={() => {resetForm();setShowForm(true)}} className="flex items-center gap-2 bg-red-500 text-white px-4 py-2.5 rounded-lg font-medium hover:bg-red-600"><Plus size={18}/> Add Product (Import)</button></div>
      <div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={18}/><input type="text" placeholder="Search products..." value={search} onChange={e => setSearch(e.target.value)} className="w-full pl-10 pr-4 py-2.5 bg-white border rounded-lg focus:ring-2 focus:ring-blue-500 outline-none"/></div>
      {showForm && (<div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4" onClick={e=>{if(e.target===e.currentTarget)resetForm()}}><div className="bg-white rounded-xl w-full max-w-md p-6"><div className="flex items-center justify-between mb-4"><h2 className="text-lg font-semibold">{editing?'Edit':'Add'} Product</h2><button onClick={resetForm}><X size={20} className="text-gray-400"/></button></div><form onSubmit={handleSubmit} className="space-y-4"><div><label className="block text-sm font-medium text-gray-700 mb-1">Name *</label><input type="text" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required className="w-full px-3 py-2 border rounded-lg outline-none" placeholder="Frozen Corn"/></div><div><label className="block text-sm font-medium text-gray-700 mb-1">Description</label><input type="text" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="w-full px-3 py-2 border rounded-lg outline-none"/></div><div className="grid grid-cols-2 gap-4"><div><label className="block text-sm font-medium text-gray-700 mb-1">Cost Price *</label><input type="number" step="0.01" min="0" value={form.costPrice} onChange={e=>setForm({...form,costPrice:e.target.value})} required className="w-full px-3 py-2 border rounded-lg outline-none"/></div><div><label className="block text-sm font-medium text-gray-700 mb-1">Selling Price *</label><input type="number" step="0.01" min="0" value={form.sellingPrice} onChange={e=>setForm({...form,sellingPrice:e.target.value})} required className="w-full px-3 py-2 border rounded-lg outline-none"/></div></div><div className="grid grid-cols-2 gap-4"><div><label className="block text-sm font-medium text-gray-700 mb-1">Quantity *</label><input type="number" min="0" value={form.stockQuantity} onChange={e=>setForm({...form,stockQuantity:e.target.value})} required className="w-full px-3 py-2 border rounded-lg outline-none"/></div><div><label className="block text-sm font-medium text-gray-700 mb-1">Unit</label><select value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})} className="w-full px-3 py-2 border rounded-lg outline-none"><option value="pcs">Pieces</option><option value="kg">Kg</option><option value="ltr">Litre</option><option value="box">Box</option><option value="pack">Pack</option></select></div></div><div className="flex gap-3 pt-2"><button type="button" onClick={resetForm} className="flex-1 px-4 py-2.5 border rounded-lg font-medium text-gray-700 hover:bg-gray-50">Cancel</button><button type="submit" disabled={saving} className="flex-1 bg-red-500 text-white px-4 py-2.5 rounded-lg font-medium hover:bg-red-600 disabled:opacity-50">{saving?'Saving...':editing?'Update':'Add Product'}</button></div></form></div></div>)}
      {loading ? <div className="flex justify-center py-16"><div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div></div> : filtered.length===0 ? <div className="text-center py-16 bg-white rounded-xl border"><Package className="mx-auto text-gray-300" size={48}/><p className="mt-4 text-gray-500">No products</p></div> : (
        <div className="bg-white rounded-xl border overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b bg-gray-50"><th className="text-left p-4 font-medium text-gray-600">Product</th><th className="text-right p-4 font-medium text-gray-600">Cost</th><th className="text-right p-4 font-medium text-gray-600">Selling</th><th className="text-right p-4 font-medium text-gray-600">Margin</th><th className="text-right p-4 font-medium text-gray-600">Stock</th><th className="text-right p-4 font-medium text-gray-600">Actions</th></tr></thead><tbody className="divide-y">{filtered.map((p:any)=>{const margin=p.sellingPrice>0?((p.sellingPrice-p.costPrice)/p.sellingPrice*100):0; return(<tr key={p.id} className="hover:bg-gray-50"><td className="p-4"><p className="font-medium text-gray-900">{p.name}</p>{p.description&&<p className="text-xs text-gray-500">{p.description}</p>}</td><td className="p-4 text-right text-red-500 font-medium">{formatCurrency(p.costPrice)}</td><td className="p-4 text-right text-green-600 font-medium">{formatCurrency(p.sellingPrice)}</td><td className="p-4 text-right"><span className={`text-xs font-medium px-2 py-1 rounded-full ${margin>0?'bg-green-50 text-green-700':'bg-red-50 text-red-700'}`}>{margin.toFixed(1)}%</span></td><td className="p-4 text-right">{restockId===p.id?(<div className="flex items-center gap-2 justify-end"><input type="number" min="1" value={restockQty} onChange={e=>setRestockQty(e.target.value)} className="w-20 px-2 py-1 border rounded text-sm" autoFocus/><button onClick={()=>handleRestock(p.id)} className="text-xs bg-red-500 text-white px-2 py-1 rounded">Add</button><button onClick={()=>setRestockId(null)} className="text-xs text-gray-500">x</button></div>):(<span className={`font-medium cursor-pointer hover:underline ${p.stockQuantity<=5?'text-red-500':'text-gray-900'}`} onClick={()=>{setRestockId(p.id);setRestockQty('')}}>{p.stockQuantity} {p.unit}</span>)}</td><td className="p-4 text-right"><div className="flex items-center gap-2 justify-end"><button onClick={()=>startEdit(p)} className="p-1.5 text-gray-400 hover:text-blue-600 rounded"><Edit2 size={14}/></button><button onClick={()=>handleDelete(p.id)} className="p-1.5 text-gray-400 hover:text-red-500 rounded"><Trash2 size={14}/></button></div></td></tr>)})}</tbody></table></div>
      )}
    </div>
  )
}
