"use client"
import { useEffect, useState } from 'react'
import { Plus, Users, Search, Edit2, Trash2, X, Phone, Mail, MapPin } from 'lucide-react'
export default function CustomersPage() {
  const [customers, setCustomers] = useState<any[]>([]); const [search, setSearch] = useState(''); const [showForm, setShowForm] = useState(false); const [editing, setEditing] = useState<any>(null); const [loading, setLoading] = useState(true); const [form, setForm] = useState({name:'',address:'',phone:'',email:''}); const [saving, setSaving] = useState(false)
  useEffect(() => { load() }, [])
  async function load() { const d = await fetch('/api/customers').then(r=>r.json()); setCustomers(Array.isArray(d)?d:[]); setLoading(false) }
  async function handleSubmit(e: React.FormEvent) { e.preventDefault(); setSaving(true); if(editing) await fetch('/api/customers',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:editing.id,...form})}); else await fetch('/api/customers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)}); resetForm(); load() }
  async function handleDelete(id:string) { if(!confirm('Delete?')) return; await fetch(`/api/customers?id=${id}`,{method:'DELETE'}); load() }
  function resetForm() { setForm({name:'',address:'',phone:'',email:''}); setEditing(null); setShowForm(false); setSaving(false) }
  function startEdit(c:any) { setForm({name:c.name,address:c.address,phone:c.phone,email:c.email}); setEditing(c); setShowForm(true) }
  const filtered = customers.filter(c => c.name.toLowerCase().includes(search.toLowerCase()) || c.phone.includes(search))
  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4"><div><h1 className="text-2xl font-bold text-gray-900">Customers</h1><p className="text-gray-500 mt-1">{customers.length} customers</p></div><button onClick={()=>{resetForm();setShowForm(true)}} className="flex items-center gap-2 bg-blue-600 text-white px-4 py-2.5 rounded-lg font-medium hover:bg-blue-700"><Plus size={18}/> Add Customer</button></div>
      <div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={18}/><input type="text" placeholder="Search..." value={search} onChange={e=>setSearch(e.target.value)} className="w-full pl-10 pr-4 py-2.5 bg-white border rounded-lg outline-none"/></div>
      {showForm && (<div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4" onClick={e=>{if(e.target===e.currentTarget)resetForm()}}><div className="bg-white rounded-xl w-full max-w-md p-6"><div className="flex items-center justify-between mb-4"><h2 className="text-lg font-semibold">{editing?'Edit':'Add'} Customer</h2><button onClick={resetForm}><X size={20} className="text-gray-400"/></button></div><form onSubmit={handleSubmit} className="space-y-4"><div><label className="block text-sm font-medium text-gray-700 mb-1">Name *</label><input type="text" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required className="w-full px-3 py-2 border rounded-lg outline-none" placeholder="Viya Hotels"/></div><div><label className="block text-sm font-medium text-gray-700 mb-1">Phone</label><input type="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} className="w-full px-3 py-2 border rounded-lg outline-none"/></div><div><label className="block text-sm font-medium text-gray-700 mb-1">Email</label><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} className="w-full px-3 py-2 border rounded-lg outline-none"/></div><div><label className="block text-sm font-medium text-gray-700 mb-1">Address</label><textarea value={form.address} onChange={e=>setForm({...form,address:e.target.value})} rows={2} className="w-full px-3 py-2 border rounded-lg outline-none resize-none"/></div><div className="flex gap-3 pt-2"><button type="button" onClick={resetForm} className="flex-1 px-4 py-2.5 border rounded-lg font-medium text-gray-700 hover:bg-gray-50">Cancel</button><button type="submit" disabled={saving} className="flex-1 bg-blue-600 text-white px-4 py-2.5 rounded-lg font-medium hover:bg-blue-700 disabled:opacity-50">{saving?'Saving...':editing?'Update':'Add'}</button></div></form></div></div>)}
      {loading ? <div className="flex justify-center py-16"><div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div></div> : filtered.length===0 ? <div className="text-center py-16 bg-white rounded-xl border"><Users className="mx-auto text-gray-300" size={48}/><p className="mt-4 text-gray-500">No customers</p></div> : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">{filtered.map((c:any)=>(<div key={c.id} className="bg-white rounded-xl border p-5 hover:shadow-md transition-shadow"><div className="flex items-start justify-between"><div className="w-10 h-10 bg-blue-50 rounded-full flex items-center justify-center"><span className="text-blue-700 font-semibold">{c.name.charAt(0).toUpperCase()}</span></div><div className="flex gap-1"><button onClick={()=>startEdit(c)} className="p-1.5 text-gray-400 hover:text-blue-600 rounded"><Edit2 size={14}/></button><button onClick={()=>handleDelete(c.id)} className="p-1.5 text-gray-400 hover:text-red-500 rounded"><Trash2 size={14}/></button></div></div><h3 className="font-semibold text-gray-900 mt-3">{c.name}</h3><div className="mt-2 space-y-1 text-sm text-gray-500">{c.phone&&<div className="flex items-center gap-2"><Phone size={12}/>{c.phone}</div>}{c.email&&<div className="flex items-center gap-2"><Mail size={12}/>{c.email}</div>}{c.address&&<div className="flex items-center gap-2"><MapPin size={12}/>{c.address}</div>}</div></div>))}</div>
      )}
    </div>
  )
}
